homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

# Enables the frontend
frontend:

http:
  api_password: !secret api_password 
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

config:

group:
# Enables support for tracking state changes over time.
history: !include_dir_merge_list history

# View all events in a logbook
logbook: !include_dir_merge_list logbook

# Track the sun
sun:

# Weather Prediction
sensor: !include_dir_merge_list sensor

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

websocket_api:

# device_tracker: !include_dir_merge_list device_tracker

light: !include_dir_merge_list light

cover: !include_dir_merge_list cover

switch: !include_dir_merge_list switch

automation: !include_dir_merge_list automation

climate:
  - platform: generic_thermostat
    name: Bedroom
    heater: switch.sonoff_1
    target_sensor: sensor.bedroom
    min_temp: 10
    max_temp: 25
    target_temp: 17
    tolerance: 0.3
    min_cycle_duration:
      minutes: 2

binary_sensor:
  - platform: aurora

scene:
  - name: Night
    entities:
      switch.fluxer: off
      light.light_bedroom: off
      light.rgb_bedroom: off
      climate.bedroom:
        temperature: 17
  - name: Flux
    entities:
      light.light_bedroom: on
      switch.fluxer: on
      light.rgb_bedroom: off
      climate.bedroom:
        temperature: 23
  - name: Red
    entities:
      light.light_bedroom: off
      switch.fluxer: off
      light.rgb_bedroom:
        brightness: 127
        rgb_color:  [255, 0, 0]
        state: on
  - name: Day
    entities:
      light.light_bedroom:
        state: on
        brightness: 255
        color_temp: 280
      switch.fluxer: off
      light.rgb_bedroom: off
      climate.bedroom:
        temperature: 23
  - name: Warm night
    entities:
      light.light_bedroom:
        brightness: 64
        color_temp: 500
        state: on
      switch.fluxer: off
      light.rgb_bedroom: off
      climate.bedroom:
        temperature: 23

ifttt:
  key: !secret ifttt_key

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

tts:
  - platform: google

recorder:
  purge_days: 2
