homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

http:
  api_password: !secret api_password
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
updater:
#discovery:
conversation:
config:
hassio:

group: !include group.yaml

sun:
  elevation: !secret elevation

sensor: !include sensor.yaml

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

websocket_api:

device_tracker:
  - platform: gpslogger

light: !include light.yaml

cover: !include cover.yaml

switch: !include switch.yaml

automation: !include_dir_merge_list automation

#emulated_hue:
#  host_ip: 192.168.1.32

climate:
  - platform: generic_thermostat
    name: Bedroom
    heater: switch.sonoff_1
    target_sensor: sensor.bedroom
    min_temp: 10
    max_temp: 25
    target_temp: 0
    tolerance: 0.3
    min_cycle_duration:
      minutes: 2

#input_slider:
#  target_day_bedroom_temperature:
#      name: Day temperature
#      initial: 22
#      min: 15
#      min: 15
#      max: 25
#      step: 1
#      icon: mdi:target

#  target_night_bedroom_temperature:
#      name: Night temperature
#      initial: 17
#      min: 15
#      max: 25
#      step: 1
#      icon: mdi:target

input_boolean:
  heater_on:
    name: Heater on
    initial: off


#device_sun_light_trigger:
#  light_group: group.pressence_trigger
#  device_group: group.people
#  light_profile: reading

#binary_sensor:
#  - platform: aurora

scene: !include scene.yaml

ifttt:
  key: !secret ifttt_key

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

tts:
  - platform: google

media_player:
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
- platform: webostv
  host: 192.168.1.8
- platform: bluesound
  hosts:
    - host: 192.168.1.40

logbook:

history:

recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.disk_use_home
      - sensor.ram_free
      - sensor.average_load_5m
      - sensor.since_last_boot
      - sensor.yr_cloudiness
      - sensor.yr_symbol
    domains:
      - automation
      - media_player
      - group
      - scene
      - zone
      - automation

shell_command:
  shutdown_pc: 'curl -k http://192.168.1.5:8000/?action=System.Shutdown'
  restart_pc: 'curl -k http://192.168.1.5:8000/?action=System.Restart'
  sleep_pc: 'curl -k http://192.168.1.5:8000/?action=System.Sleep'
  hibernate_pc: 'curl -k http://192.168.1.5:8000/?action=System.Hibernate'
