- platform: mqtt
  name: "Light Bedroom"
  state_topic: 'soverom/light2'
  command_topic: 'soverom/light/switch'
  brightness_state_topic: 'soverom/light/brightness2'
  brightness_command_topic: 'soverom/light/brightness/set'
  color_temp_state_topic: 'soverom/light/colortemp2'
  color_temp_command_topic: 'soverom/light/colortemp/set'
  brightness_scale: 1023

- platform: mqtt
  name: "RGB Bedroom"
  state_topic: "soverom/rgb1/light/status2"
  command_topic: "soverom/rgb1/light/switch"
  brightness_state_topic: "soverom/rgb1/brightness/status2"
  brightness_command_topic: "soverom/rgb1/brightness/set"
  rgb_state_topic: "soverom/rgb1/rgb/status2"
  rgb_command_topic: "soverom/rgb1/rgb/set"
  effect_state_topic: "soverom/rgb1/effect/status"
  effect_command_topic: "soverom/rgb1/effect/set"
  effect_list:
    - RGB
    - FADE
  brightness_scale: 1023
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
