
- platform: yr
  monitored_conditions:
    - temperature
    - cloudiness
    - symbol

- platform: fastdotcom
  hour: 4
  #manual: true

- platform: systemmonitor
  resources:
  - type: load_5m
  - type: since_last_boot
  
- platform: onewire
  names:
    28031664daffff_temperature: Bedroom
    
# - platform: dht
  # sensor: DHT11
  # pin: 22
  # temperature_offset: 0
  # humidity_offset: 0
  # monitored_conditions:
    # - temperature
    # - humidity

- platform: mqtt
  name: "Sonoff1 RSSI"
  state_topic: "tele/sonoff1/RSSI"
  
- platform: mqtt
  name: "Sonoff1 Time"
  state_topic: "tele/sonoff1/TIME"
  
- platform: mqtt
  name: "Sonoff1 UPTIME"
  state_topic: "tele/sonoff1/UPTIME"
    
- platform: mqtt
  name: "Sonoff1 telemetry state"
  state_topic: "tele/sonoff1/POWER"
  expire_after: 600
  
- platform: mqtt
  name: "Sonoff2 RSSI"
  state_topic: "tele/sonoff2/RSSI"
  
- platform: mqtt
  name: "Sonoff2 Time"
  state_topic: "tele/sonoff2/TIME"
  
- platform: mqtt
  name: "Sonoff2 UPTIME"
  state_topic: "tele/sonoff2/UPTIME"
    
- platform: mqtt
  name: "Sonoff2 telemetry state"
  state_topic: "tele/sonoff2/POWER"
  expire_after: 600
  
- platform: mqtt
  state_topic: 'octoprint/event/PrinterStateChanged'
  name: 'Printer Status'
  value_template: '{{ value_json.state_string }}'

- platform: template
  sensors:
    battery_5x:
      friendly_name: "Nexus 5x battery"
      unit_of_measurement: '%'
      value_template: >-
        {% if states.device_tracker["0218fe5d62ca36f0"] %}
          {{ states.device_tracker["0218fe5d62ca36f0"].attributes.battery }}
        {% endif %}

    activity_5x:
      friendly_name: "Nexus 5x activity"
      value_template:  >-
        {% if states.device_tracker["0218fe5d62ca36f0"] %}
          {{ states.device_tracker["0218fe5d62ca36f0"].attributes.activity }}
        {% endif %}
        
    speed_5x:
      friendly_name: "Nexus 5x speed"
      value_template:  >-
        {% if states.device_tracker["0218fe5d62ca36f0"] %}
          {{ states.device_tracker["0218fe5d62ca36f0"].attributes.speed }}
        {% endif %}