- platform: mqtt
  state_topic: "bedroom/rollers"
  command_topic: "bedroom/rollers/set"
  name: "Bedroom Roller blinds"
  qos: 0
  retain: true
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "open"
  state_closed: "closed"
  optimistic: false
